import type { Position } from "./types";

export const STATES = [
  "Alabama",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Florida",
  "Georgia",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Nebraska",
  "Nevada",
  "New Mexico",
  "New York",
  "North Carolina",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "South Carolina",
  "Tennessee",
  "Texas",
  "Utah",
  "Virginia",
  "Washington",
  "Wisconsin",
] as const;

export const CITIES = [
  "Aster Falls",
  "Ashenford",
  "Avalon Pines",
  "Barrowgate",
  "Bellwether",
  "Briar Harbor",
  "Brightmoor",
  "Brindle Creek",
  "Buckthorn",
  "Canyon Mesa",
  "Cedarwatch",
  "Cliffhaven",
  "Cloudbreak",
  "Copper Bend",
  "Coral Junction",
  "Crescent Mills",
  "Driftwood",
  "Dunewick",
  "East Rook",
  "Eldermere",
  "Emberton",
  "Fairhollow",
  "Fallow Ridge",
  "Farspring",
  "Foxglade",
  "Frostbridge",
  "Garnet Shoals",
  "Granite Bay",
  "Greenbarrow",
  "Hawthorne",
  "Hazelport",
  "Highbank",
  "Hollowford",
  "Ironvale",
  "Ivory Glen",
  "Juniper City",
  "Kestrel Point",
  "Kingston Ridge",
  "Lake Marrow",
  "Larkspur",
  "Laurel Forge",
  "Limestone Reach",
  "Lowland Gate",
  "Maplewick",
  "Meadowfall",
  "Millstone",
  "Mistral Bay",
  "Mossfield",
  "North Argent",
  "Northvale",
  "Oakmere",
  "Orchard Gate",
  "Pineforge",
  "Pinnacle Falls",
  "Prairie Hollow",
  "Quartz Hill",
  "Rainmere",
  "Redbank",
  "Riverglass",
  "Rookhaven",
  "Rosewick",
  "Sable Junction",
  "Sage Hollow",
  "Silver Run",
  "South Fen",
  "Starling Bay",
  "Stonebridge",
  "Stormwell",
  "Sunbarrow",
  "Tanglewood",
  "Thornfield",
  "Trident Falls",
  "Twin Lanterns",
  "Union Hollow",
  "Valeport",
  "Vesper",
  "Violet Ridge",
  "Waterford Hollow",
  "Westhaven",
  "Willowmere",
  "Windcrest",
  "Wintergate",
  "Yarrow",
  "Amberwell",
  "Birch Crossing",
  "Blackstone Yard",
  "Bluefen",
  "Cinder Ridge",
  "Clearwater Forge",
  "Cloverbank",
  "Crimson Harbor",
  "Dawnmere",
  "Deepwood",
  "Elmspire",
  "Fieldstone",
  "Foxrun",
  "Glacier Bend",
  "Goldleaf",
  "Hearthwick",
  "Honeywell",
  "Iron Orchard",
  "Jasper Gate",
  "Kingswell",
  "Lantern Creek",
  "Moonvale",
  "Nettleford",
  "Osprey Bend",
  "Palisade",
  "Ridgewater",
  "Seabright",
  "Timberline",
  "Umber Falls",
  "Verdant Run",
  "Warden Hill",
  "Whitecap",
  "Yew Harbor",
  "Arbor Crest",
  "Bastion Springs",
  "Bluewater Bluff",
  "Cannon Ridge",
  "Cypress Vale",
  "Eagleford",
  "Falcon Rest",
  "Glasswater",
  "Harborwick",
  "Ironwood Flats",
  "Keystone Bay",
  "Marigold Mesa",
  "New Alder",
  "Peregrine Falls",
  "Redwood Crossing",
  "Summit Grove",
  "Thistle Bend",
  "Waverly Shoals",
  "Westmere",
  "Zephyr Springs",
] as const;

export const FIRST_NAMES = [
  "Andre",
  "Ari",
  "Asa",
  "August",
  "Bennett",
  "Blaise",
  "Bodie",
  "Bram",
  "Caleb",
  "Callan",
  "Camden",
  "Cassian",
  "Darius",
  "Dawson",
  "Deacon",
  "Devin",
  "Eli",
  "Ellis",
  "Emmett",
  "Ezra",
  "Felix",
  "Finn",
  "Foster",
  "Gavin",
  "Gideon",
  "Grant",
  "Griffin",
  "Hayes",
  "Holden",
  "Hudson",
  "Isaiah",
  "Ishaan",
  "Ivan",
  "Jalen",
  "Jonas",
  "Jules",
  "Kieran",
  "Kai",
  "Kellan",
  "Knox",
  "Luca",
  "Landon",
  "Lawson",
  "Leon",
  "Malik",
  "Marlon",
  "Micah",
  "Miles",
  "Nico",
  "Noel",
  "Nolan",
  "Owen",
  "Orion",
  "Otis",
  "Porter",
  "Preston",
  "Price",
  "Quentin",
  "Quincy",
  "Quinn",
  "Rafael",
  "Reed",
  "Remy",
  "Roman",
  "Silas",
  "Soren",
  "Sterling",
  "Tariq",
  "Tate",
  "Theo",
  "Tobias",
  "Uri",
  "Uriah",
  "Usher",
  "Vance",
  "Vaughn",
  "Victor",
  "Wes",
  "Warren",
  "Weston",
  "Xavier",
  "Xander",
  "Xavi",
  "Yusuf",
  "Yael",
  "York",
  "Zane",
  "Zayden",
  "Zeke",
] as const;

export const LAST_NAMES = [
  "Aldridge",
  "Ashford",
  "Aster",
  "Baylor",
  "Beckett",
  "Benton",
  "Briar",
  "Cavanaugh",
  "Calloway",
  "Carver",
  "Crest",
  "Dorsey",
  "Drake",
  "Dunlap",
  "Ellison",
  "Ember",
  "Everly",
  "Fletcher",
  "Fairchild",
  "Fenwick",
  "Frost",
  "Graves",
  "Gable",
  "Garnett",
  "Greer",
  "Hollis",
  "Hale",
  "Hartwell",
  "Huxley",
  "Irving",
  "Ives",
  "Iverson",
  "Jennings",
  "Jasper",
  "Jensen",
  "Kincaid",
  "Keaton",
  "Keller",
  "Kestrel",
  "Lang",
  "Ledger",
  "Lockhart",
  "Lowell",
  "Maddox",
  "Marrow",
  "Merrick",
  "Montrose",
  "Nash",
  "North",
  "Novak",
  "Osborne",
  "Oakley",
  "Ormond",
  "Pruitt",
  "Parker",
  "Pike",
  "Prescott",
  "Quill",
  "Quarry",
  "Quinlan",
  "Ramsey",
  "Redford",
  "Reeves",
  "Ridge",
  "Sutter",
  "Sable",
  "Sawyer",
  "Stone",
  "Talon",
  "Tanner",
  "Thorne",
  "Tiller",
  "Upshaw",
  "Underwood",
  "Upton",
  "Vega",
  "Vale",
  "Voss",
  "Whitley",
  "Warden",
  "Westfall",
  "Wilder",
  "York",
  "Yates",
  "Youngblood",
  "Ziegler",
  "Zeller",
  "Zephyr",
] as const;

export const MASCOTS = [
  "Wardens",
  "Stags",
  "Pilots",
  "Gales",
  "Miners",
  "Comets",
  "Founders",
  "Sentinels",
  "Ravens",
  "Forge",
  "Summits",
  "Lancers",
  "Bison",
  "Spires",
  "Monarchs",
  "Mariners",
  "Cyclones",
  "Pioneers",
  "Voltage",
  "Hammers",
  "Condors",
  "Fleet",
  "Tides",
  "Timber",
  "Owls",
  "Rockets",
  "Knights",
  "Vipers",
  "Seawolves",
  "Copperheads",
  "Aviators",
  "Bastions",
  "Bluehawks",
  "Breakers",
  "Bulwarks",
  "Corsairs",
  "Drifters",
  "Firebirds",
  "Greyhounds",
  "Ironclads",
  "Keystones",
  "Mammoths",
  "Nightfall",
  "Outriders",
  "Prairie Kings",
  "Redtails",
  "Ridgebacks",
  "Skyhawks",
  "Thunderbirds",
  "Wildcats",
] as const;

export const CONFERENCE_NAMES = [
  "Northern Circuit",
  "Sunforge League",
  "Great Plains Union",
  "Atlantic Crown",
  "Mountain Accord",
  "Delta Alliance",
  "Pacific Foundry",
] as const;

export const AWARD_NAMES: Record<string, string> = {
  overall: "Iron Lantern Trophy",
  qb: "Signal Caller Crown",
  rb: "Ground Hammer Medal",
  wr: "Skyline Receiver Cup",
  ol: "Anchor Line Shield",
  dl: "Forge Front Trophy",
  lb: "Middle Watch Award",
  db: "No-Fly Laurel",
  kicker: "Golden Boot Pin",
  freshman: "First Spark Honor",
  coach: "Circuit Architect Award",
};

export const POSITION_LABELS: Record<Position, string> = {
  QB: "Quarterback",
  HB: "Halfback",
  WR: "Receiver",
  TE: "Tight End",
  OL: "Offensive Line",
  DL: "Defensive Line",
  LB: "Linebacker",
  CB: "Corner",
  S: "Safety",
  K: "Kicker",
  P: "Punter",
};

export const BOWL_NAMES = [
  "Cinder Bowl",
  "Harbor Bowl",
  "Copper Bowl",
  "Lantern Bowl",
  "Timber Bowl",
  "Foundry Bowl",
  "Orchard Bowl",
  "Summit Bowl",
  "Crown Bowl",
] as const;

export const SCHEMES = [
  "Tempo Spread",
  "Power Option",
  "Air Raid",
  "Balanced Pro",
  "Zone Pressure",
  "Nickel Swarm",
  "Tite Front",
  "Field Control",
] as const;
