import type { Position } from "./types";

export const STATES = [
  "Alabama",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Florida",
  "Georgia",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Nebraska",
  "Nevada",
  "New Mexico",
  "New York",
  "North Carolina",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "South Carolina",
  "Tennessee",
  "Texas",
  "Utah",
  "Virginia",
  "Washington",
  "Wisconsin",
] as const;

export const CITIES = [
  "Aster Falls",
  "Briar Harbor",
  "Canyon Mesa",
  "Copper Bend",
  "Driftwood",
  "East Rook",
  "Emberton",
  "Foxglade",
  "Granite Bay",
  "Hawthorne",
  "Ironvale",
  "Juniper City",
  "Kingston Ridge",
  "Lake Marrow",
  "Millstone",
  "North Argent",
  "Oakmere",
  "Pineforge",
  "Quartz Hill",
  "Redbank",
  "Silver Run",
  "Trident Falls",
  "Union Hollow",
  "Vesper",
  "Westhaven",
  "Yarrow",
] as const;

export const FIRST_NAMES = [
  "Andre",
  "Bennett",
  "Caleb",
  "Darius",
  "Eli",
  "Felix",
  "Gavin",
  "Hayes",
  "Isaiah",
  "Jalen",
  "Kieran",
  "Luca",
  "Malik",
  "Nico",
  "Owen",
  "Porter",
  "Quentin",
  "Rafael",
  "Silas",
  "Tariq",
  "Uri",
  "Vance",
  "Wes",
  "Xavier",
  "Yusuf",
  "Zane",
] as const;

export const LAST_NAMES = [
  "Aldridge",
  "Baylor",
  "Cavanaugh",
  "Dorsey",
  "Ellison",
  "Fletcher",
  "Graves",
  "Hollis",
  "Irving",
  "Jennings",
  "Kincaid",
  "Lang",
  "Maddox",
  "Nash",
  "Osborne",
  "Pruitt",
  "Quill",
  "Ramsey",
  "Sutter",
  "Talon",
  "Upshaw",
  "Vega",
  "Whitley",
  "York",
  "Ziegler",
] as const;

export const MASCOTS = [
  "Wardens",
  "Stags",
  "Pilots",
  "Gales",
  "Miners",
  "Comets",
  "Founders",
  "Sentinels",
  "Ravens",
  "Forge",
  "Summits",
  "Lancers",
  "Bison",
  "Spires",
  "Monarchs",
  "Mariners",
  "Cyclones",
  "Pioneers",
  "Voltage",
  "Hammers",
  "Condors",
  "Fleet",
  "Tides",
  "Timber",
  "Owls",
  "Rockets",
  "Knights",
  "Vipers",
  "Seawolves",
  "Copperheads",
] as const;

export const CONFERENCE_NAMES = [
  "Northern Circuit",
  "Sunforge League",
  "Great Plains Union",
  "Atlantic Crown",
  "Mountain Accord",
  "Delta Alliance",
  "Pacific Foundry",
] as const;

export const AWARD_NAMES: Record<string, string> = {
  overall: "Iron Lantern Trophy",
  qb: "Signal Caller Crown",
  rb: "Ground Hammer Medal",
  wr: "Skyline Receiver Cup",
  ol: "Anchor Line Shield",
  dl: "Forge Front Trophy",
  lb: "Middle Watch Award",
  db: "No-Fly Laurel",
  kicker: "Golden Boot Pin",
  freshman: "First Spark Honor",
  coach: "Circuit Architect Award",
};

export const POSITION_LABELS: Record<Position, string> = {
  QB: "Quarterback",
  HB: "Halfback",
  WR: "Receiver",
  TE: "Tight End",
  OL: "Offensive Line",
  DL: "Defensive Line",
  LB: "Linebacker",
  CB: "Corner",
  S: "Safety",
  K: "Kicker",
  P: "Punter",
};

export const BOWL_NAMES = [
  "Cinder Bowl",
  "Harbor Bowl",
  "Copper Bowl",
  "Lantern Bowl",
  "Timber Bowl",
  "Foundry Bowl",
  "Orchard Bowl",
  "Summit Bowl",
  "Crown Bowl",
] as const;

export const SCHEMES = [
  "Tempo Spread",
  "Power Option",
  "Air Raid",
  "Balanced Pro",
  "Zone Pressure",
  "Nickel Swarm",
  "Tite Front",
  "Field Control",
] as const;
